sonar.projectKey=poc-kubernetes-local
sonar.projectName=POC Kubernetes Local DevOps
sonar.sources=app
sonar.tests=app/tests
sonar.exclusions=app/tests/**
sonar.test.inclusions=app/tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=app/coverage.xml
